/**
 * Reads Claude Code's session transcript (JSONL at the hook payload's
 * `transcript_path`) into the turn list MindFerry's `archive_thread` takes.
 *
 * That file's entry format is internal and undocumented — Claude Code's own
 * docs warn it "changes between versions". Every read here is defensive: a
 * line or entry it does not recognize is skipped, never thrown, so a format
 * change degrades to a thinner archive instead of a failed hook. What it
 * keeps is what a person would recognize as the conversation: what the user
 * typed and what Claude said. Thinking, tool calls and tool results,
 * subagent traffic, slash-command wrappers and harness-generated messages
 * are left out.
 */
import { readFileSync, existsSync } from 'node:fs';
import { basename } from 'node:path';

/** Text a message wraps around something the user did not type. */
const HARNESS_TEXT_PREFIXES = [
  '<command-name>',
  '<command-message>',
  '<local-command',
  '<task-notification>',
  '<system-reminder>',
  'Caveat: The messages below were generated by the user while running local commands',
  'This session is being continued from a previous conversation',
];

const MAX_TITLE_LENGTH = 80;

function textOf(content) {
  if (typeof content === 'string') {
    return content;
  }
  if (!Array.isArray(content)) {
    return '';
  }
  return content
    .filter((block) => block && block.type === 'text' && typeof block.text === 'string')
    .map((block) => block.text)
    .join('\n');
}

function isHarnessText(text) {
  const start = text.trimStart();
  return HARNESS_TEXT_PREFIXES.some((prefix) => start.startsWith(prefix));
}

/** A person's own message: not a tool result, not meta, not from a subagent,
 *  and not one of the non-human origins (task notifications, peers, schedules). */
function humanText(entry) {
  if (entry.isSidechain || entry.isMeta) {
    return '';
  }
  const origin = entry.origin?.kind;
  if (origin !== undefined && origin !== 'human') {
    return '';
  }
  const text = textOf(entry.message?.content).trim();
  return text && !isHarnessText(text) ? text : '';
}

function assistantText(entry) {
  if (entry.isSidechain || entry.isApiErrorMessage) {
    return '';
  }
  return textOf(entry.message?.content).trim();
}

function parseLine(line) {
  if (!line.trim()) {
    return undefined;
  }
  try {
    return JSON.parse(line);
  } catch {
    return undefined;
  }
}

function collapse(text, maxLength) {
  const flat = text.trim().replace(/\s+/g, ' ');
  return flat.length <= maxLength ? flat : `${flat.slice(0, maxLength).trimEnd()}…`;
}

/**
 * The conversation as alternating turns: every assistant text block between
 * two user messages is joined into one assistant turn, so a reply that was
 * interleaved with tool calls reads as the single answer it was.
 *
 * @param {string | undefined} transcriptPath
 * @returns {{ messages: { role: 'user' | 'assistant', text: string }[], aiTitle?: string }}
 */
export function readConversation(transcriptPath) {
  const messages = [];
  let aiTitle;
  if (!transcriptPath || !existsSync(transcriptPath)) {
    return { messages, aiTitle };
  }

  let pendingAssistant = [];
  const flushAssistant = () => {
    if (pendingAssistant.length > 0) {
      messages.push({ role: 'assistant', text: pendingAssistant.join('\n\n') });
      pendingAssistant = [];
    }
  };

  for (const line of readFileSync(transcriptPath, 'utf8').split('\n')) {
    const entry = parseLine(line);
    if (!entry) {
      continue;
    }
    if (entry.type === 'ai-title' && typeof entry.aiTitle === 'string' && entry.aiTitle.trim()) {
      aiTitle = entry.aiTitle.trim();
      continue;
    }
    if (entry.type === 'user') {
      const text = humanText(entry);
      if (text) {
        flushAssistant();
        messages.push({ role: 'user', text });
      }
      continue;
    }
    if (entry.type === 'assistant') {
      const text = assistantText(entry);
      if (text && messages.length > 0) {
        pendingAssistant.push(text);
      }
    }
  }
  flushAssistant();
  return { messages, aiTitle };
}

/**
 * Fits a conversation under the hub's limits (`archive_thread` allows 200000
 * characters a turn and `contextHub.mcp.maxArchiveBytes` bytes in all). Long
 * turns are cut first; if that is not enough, the oldest turns are dropped
 * and the first kept turn says so, so the record never claims to be whole
 * when it is not.
 *
 * @param {{ role: 'user' | 'assistant', text: string }[]} messages
 * @param {{ maxBytes: number, maxTurnChars: number, maxTurns: number }} limits
 */
export function fitToLimits(messages, { maxBytes, maxTurnChars, maxTurns }) {
  const cut = messages.map((message) =>
    message.text.length > maxTurnChars
      ? {
          ...message,
          text: `${message.text.slice(0, maxTurnChars)}\n\n[… cut: ${message.text.length - maxTurnChars} more characters]`,
        }
      : message,
  );

  const kept = [];
  let bytes = 0;
  for (let i = cut.length - 1; i >= 0 && kept.length < maxTurns; i--) {
    const size = Buffer.byteLength(cut[i].text);
    if (bytes + size > maxBytes) {
      break;
    }
    bytes += size;
    kept.unshift(cut[i]);
  }

  const dropped = cut.length - kept.length;
  if (dropped === 0 || kept.length === 0) {
    return { messages: kept, dropped };
  }
  const [first, ...rest] = kept;
  const marker = `[earlier conversation not archived: ${dropped} turn(s) omitted to fit the hub's size limit]`;
  return { messages: [{ ...first, text: `${marker}\n\n${first.text}` }, ...rest], dropped };
}

/** A title a person can find again: Claude Code's own session title when the
 *  transcript has one, else the opening request, prefixed with the project. */
export function conversationTitle({ aiTitle, messages, cwd }) {
  const project = cwd ? basename(cwd) : '';
  const opening = messages.find((message) => message.role === 'user')?.text ?? '';
  const subject = aiTitle ?? (opening ? collapse(opening, MAX_TITLE_LENGTH) : 'Session');
  return project ? `${subject} — ${project}` : subject;
}
